//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminVivienda2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASOC_CONTRATOS_SERVICIOS
    {
        public int Id_Contrato { get; set; }
        public int Id_Servicio { get; set; }
        public decimal MesAnt { get; set; }
        public decimal MesAct { get; set; }
        public decimal MesVen { get; set; }
        public bool Activo { get; set; }
    
        public virtual TBL_CONTRATOS TBL_CONTRATOS { get; set; }
        public virtual TBL_SERVICIOS TBL_SERVICIOS { get; set; }
    }
}
