//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminVivienda2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_CONDOMINIOS
    {
        public int Id_Condominio { get; set; }
        public string Condominio { get; set; }
        public string DemMun { get; set; }
        public string Colonia { get; set; }
        public Nullable<int> Cp { get; set; }
        public string Clave { get; set; }
        public Nullable<int> Id_Estado { get; set; }
        public bool Activo { get; set; }
    
        public virtual CAT_ESTADOS CAT_ESTADOS { get; set; }
    }
}
