//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminVivienda2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SERVICIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_SERVICIOS()
        {
            this.ASOC_CONTRATOS_SERVICIOS = new HashSet<ASOC_CONTRATOS_SERVICIOS>();
        }
    
        public int Id_Servicio { get; set; }
        public string Servicios { get; set; }
        public bool Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASOC_CONTRATOS_SERVICIOS> ASOC_CONTRATOS_SERVICIOS { get; set; }
    }
}
