//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminVivienda.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdminEntities1 : DbContext
    {
        public AdminEntities1()
            : base("name=AdminEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAT_CONDOMINIO> CAT_CONDOMINIO { get; set; }
        public virtual DbSet<CAT_ESTADOS> CAT_ESTADOS { get; set; }
        public virtual DbSet<CAT_PERIL> CAT_PERIL { get; set; }
        public virtual DbSet<CAT_PERSONAS> CAT_PERSONAS { get; set; }
        public virtual DbSet<CAT_TIPOVIVIENDA> CAT_TIPOVIVIENDA { get; set; }
        public virtual DbSet<CAT_VIVIENDA> CAT_VIVIENDA { get; set; }
        public virtual DbSet<CAT_CONTRATO> CAT_CONTRATO { get; set; }
    }
}
