//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminVivienda.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_DocumentosCondominio
    {
        public int Id_DocumentoCondominio { get; set; }
        public int Id_Condominio { get; set; }
        public string DocumentoCondominio { get; set; }
        public string Descripcion { get; set; }
        public int Id_TipoDocumento { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FechaSubida { get; set; }
        public int Id_PersonaUpload { get; set; }
        public string Ruta { get; set; }
    
        public virtual CAT_CONDOMINIO CAT_CONDOMINIO { get; set; }
        public virtual CAT_TIPODOCUMENTO CAT_TIPODOCUMENTO { get; set; }
    }
}
